import Head from 'next/head'
import { Search } from '@/src/components/search'
import { Header } from '@/src/components/header'
import * as C from './styled_td'


export default function Home() {
  return (
    <>
      <Head>
        <title>ChatGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
      <C.Container>
        <C.Box>
          <Header/>
          <Search search={''} setSearch={[]} handleSubmit={function (): void {
            throw new Error('Function not implemented.')
          } } setText={''} text={''} tipo={false} block={false}/>
        </C.Box>
      </C.Container>
    </>
  )
}
